/** Editable Mod Tree recommendation UI strings. */
export const recommendationCopy = {
  ko: {
    price: "가격",
    contentUnlock: "컨텐츠 해금", featureUpgrade: "기능 강화", unlockConditions: "해금 조건",
    countSetting: "Mod Tree 추천 개수", countHelp: "기본 3개 · 1~10개. 추천 목록과 지도 강조에 함께 적용됩니다.", countSaveFailed: "추천 개수를 저장하지 못했습니다. 현재 화면에는 적용됐지만 새로고침하면 유지되지 않을 수 있습니다.",
    toolsLabel: "Mod Tree 도구", backupTitle: "백업", bulkApplied: "입력한 레벨을 반영했습니다.", restored: "백업을 불러왔습니다.", restoreCancelled: "파일을 읽는 동안 기록이 바뀌어 복원을 취소했습니다. 다시 불러와 주세요.",
    effectValueHelp: "현재 레벨 → 다음 레벨의 게임 효과. 다른 진행도는 현재 입력값으로 고정합니다.",
    effectUncertain: "현재 게임의 효과 공식 또는 필요한 진행도를 확인해야 합니다.", needsCheck: "인게임 확인 필요", inputNeeded: "진행도 입력 필요",
    overview: "현재 Mod 효과", overviewHelp: "입력한 Mod 레벨의 효과", overviewPartial: "미확인 효과는 합계에서 제외됩니다. Wiki 항목은 최신 게임과 추가 대조가 필요합니다.", overviewEmpty: "합산할 수 있는 효과가 없습니다.", partial: "부분 합계", controls: "지도 사용법",
    nodeInfo: "노드 정보", purchaseHelp: "웹에서만 1레벨 구매합니다. 실제 게임은 바뀌지 않습니다.", doubleClickHelp: "노드 더블클릭: 웹에서 1레벨 구매", purchaseDone: "웹 구매 완료", pendingBudget: "Enter 또는 다른 곳을 클릭하면 MP를 반올림해 적용합니다.", moreOptions: "계산 기준 / 입력 도움말",
    states: { unknown: "기록 확인 중", locked: "잠김", unpurchased: "미구매 · 해금됨", purchased: "구매함", maxed: "최대 레벨", capped: "구매함 · 웹 입력 상한 (게임 최대 아님)" },
    stateLegend: "짙은 회색: 잠김 · 옅은 회색: 미구매 · 초록: 구매함 · 빨강: 최대 레벨",
    levelLegend: "노드 안: 코드 · 아래: 현재/최대 레벨 · ∞: 상한 없는 노드",
    first: "1순위 추천", jumpTop: "1순위로 이동", legend: "밝은 테마색 파동: 추천 노드 · 대비색: 1순위",
    title: "업그레이드 추천", budget: "보유 MP", budgetHelp: "입력·구매 후 잔액·불러온 기록을 모두 소수 둘째 자리까지 반올림해 저장합니다. 지수 표기는 가수를 반올림합니다: 1.3425e50 → 1.34e50. 숨겨진 정밀 잔액은 두지 않습니다. 필요하면 게임에 보이는 잔액을 다시 입력하세요. 1e10000 미만까지 지원합니다.",
    roundedPlan: "매 단계 잔액을 반올림합니다. 계획 비용 합계와 처음·마지막 MP 차이는 다를 수 있습니다.",
    costImportance: "비용 중요도", costHelp: "시트 기준: 0%는 효과 점수만, 100%는 현재 MP 대비 가격 여유를 최대 반영합니다. 전역 최적해가 아닌 다음 1레벨의 탐욕적 추천입니다.",
    profileHelp: "저장한 가중치·플레이어/함선 진행도로 계산합니다. 미입력 진행도·노드 레벨은 0으로 간주합니다. G01의 Software Tech는 MK1~8 합계입니다.",
    next: "지금 가능한 추천", empty: "현재 MP·레벨·제외 설정에서 추천할 수 있는 노드가 없습니다.", level: "현재 레벨", nextCost: "다음 비용", power: "효과 점수 (log₁₀)", score: "추천 점수", prerequisites: "필요한 선행 노드", unlocked: "선행 조건 충족", maxed: "최대 레벨", ignored: "추천에서 제외", locked: "잠김", short: "MP 부족", priority: "시트 우선 해금", unavailable: "계산 확인 필요", effects: "다음 레벨 효과", noEffects: "표시할 수치 효과 없음 · 해금/편의 노드", focus: "지도에서 보기", applyOne: "구매", localOnly: "구매·더블클릭·계획 반영은 이 웹의 레벨과 MP 기록만 바꿉니다. 실제 게임이나 재화는 건드리지 않습니다.",
    invalidBudget: "MP는 0 이상, 1e10000 미만의 숫자로 입력해 주세요.", invalidLevel: "0부터 최대 레벨까지 정수로 입력해 주세요.", invalid: "입력 오류를 수정하면 추천 계산을 재개합니다.",
    planTitle: "구매 계획", steps: "최대 단계", buildPlan: "계획 계산", computing: "계산 중…", applyPlan: "계획을 웹 기록에 반영", undo: "마지막 반영 되돌리기", remaining: "남는 MP", spent: "계획 비용", planLimit: "설정한 단계 수에서 중단했습니다. 전역 최적 구매 계획은 아닙니다.", planEnd: "현재 조건에서 더 추천할 수 있는 구매가 없습니다.",
    storageFailed: "브라우저 저장소를 읽거나 저장하지 못했습니다. 새로고침 전에 백업을 내려받아 주세요.", saved: "이 브라우저에 자동 저장", loading: "기록 불러오는 중…", calculationsFailed: "일부 노드의 입력 또는 수식을 확인해야 합니다. 해당 노드는 추천에서 제외됩니다.",
    bulk: "레벨 일괄 입력", bulkHelp: "한 줄에 A01=5처럼 입력합니다. 적은 코드만 변경하며, 나머지는 유지합니다.", bulkApply: "입력한 레벨 반영", bulkInvalid: "코드·레벨을 확인해 주세요. 중복 코드도 허용하지 않습니다.", backup: "백업 내려받기", restore: "백업 불러오기", restoreInvalid: "올바른 Mod Tree v1 백업이 아닙니다. 기존 기록은 변경하지 않았습니다.",
    source: "수식 출처", method: "추천 점수 = log₁₀(Power) × [비용 중요도 × log₁₀(MP/비용) + (1 − 비용 중요도)]. A02·A03·G22는 시트의 우선 해금 규칙을 적용합니다. 게임 효율이 아닌 시트의 가중 휴리스틱입니다.",
  },
  en: {
    price: "Price",
    contentUnlock: "Content unlock", featureUpgrade: "Feature upgrade", unlockConditions: "Unlock requirements",
    countSetting: "Mod Tree recommendation count", countHelp: "Default: 3 · Range: 1–10. Applies to the list and map highlights.", countSaveFailed: "Could not save the recommendation count. It applies now but may not persist after reload.",
    toolsLabel: "Mod Tree tools", backupTitle: "Backup", bulkApplied: "Entered levels applied.", restored: "Backup restored.", restoreCancelled: "Records changed while reading the file. Import was cancelled; try again.",
    effectValueHelp: "Current → next level game effects, with other progress fixed.",
    effectUncertain: "The current game formula or required progress still needs confirmation.", needsCheck: "Game check needed", inputNeeded: "Progress input needed",
    overview: "Current Mod effects", overviewHelp: "Effects of entered Mod levels", overviewPartial: "Unconfirmed effects are excluded. Wiki rules still need comparison with the current game.", overviewEmpty: "No effects available to aggregate.", partial: "Partial total", controls: "Map controls",
    nodeInfo: "Node information", purchaseHelp: "Buy one level on this website only. The actual game is not changed.", doubleClickHelp: "Double-click a node: buy one level locally", purchaseDone: "Local purchase completed", pendingBudget: "Press Enter or leave the field to round and apply MP.", moreOptions: "Calculation / input help",
    states: { unknown: "Loading records", locked: "Locked", unpurchased: "Unpurchased · unlocked", purchased: "Purchased", maxed: "Max level", capped: "Purchased · Web input limit (not game maximum)" },
    stateLegend: "Dark gray: locked · Gray: unpurchased · Green: purchased · Red: max level",
    levelLegend: "Inside: code · Below: current/max level · ∞: unlimited node",
    first: "Top recommendation", jumpTop: "Find top pick", legend: "Bright theme ripple: recommended · Contrast color: top pick",
    title: "Upgrade recommendations", budget: "Available MP", budgetHelp: "Input, post-purchase balances and imported saves are rounded to two decimal places (the mantissa for scientific notation): 1.3425e50 → 1.34e50. No hidden precise balance is kept. Re-enter the balance shown in game when needed. Supports values below 1e10000.",
    roundedPlan: "The balance is rounded after each step. Total costs can differ from the initial minus final MP.",
    costImportance: "Cost importance", costHelp: "Sheet heuristic: 0% ranks effect power only; 100% fully weighs the logarithmic budget margin. Greedy next-level ranking, not a global optimum.",
    profileHelp: "Uses saved weights and player/ship progress. Missing progress and node levels count as zero. G01 Software Tech uses the MK1–8 total.",
    next: "Available recommendations", empty: "No eligible recommendations at these MP, levels and exclusions.", level: "Current level", nextCost: "Next cost", power: "Effect score (log₁₀)", score: "Recommendation score", prerequisites: "Missing prerequisites", unlocked: "Prerequisites met", maxed: "Max level", ignored: "Exclude from recommendations", locked: "Locked", short: "Insufficient MP", priority: "Sheet priority unlock", unavailable: "Check calculation", effects: "Next-level effects", noEffects: "No numeric effect · unlock/utility node", focus: "Show on map", applyOne: "Buy", localOnly: "Buy, double-click, and apply plan only update this website's levels and MP records. They never control the actual game or spend real resources.",
    invalidBudget: "Enter MP from zero to below 1e10000.", invalidLevel: "Enter an integer from zero to the level limit.", invalid: "Fix the input to resume recommendations.",
    planTitle: "Purchase plan", steps: "Step limit", buildPlan: "Calculate plan", computing: "Calculating…", applyPlan: "Apply plan locally", undo: "Undo last application", remaining: "Remaining MP", spent: "Plan cost", planLimit: "Stopped at your step limit. This is not a globally optimal plan.", planEnd: "No more recommended purchases under the current conditions.",
    storageFailed: "Browser storage could not be read or saved. Export a backup before refreshing.", saved: "Auto-saved in this browser", loading: "Loading records…", calculationsFailed: "Some inputs or formulas need checking. Affected nodes are excluded from recommendations.",
    bulk: "Bulk levels", bulkHelp: "One code per line, e.g. A01=5. Only entered codes change; all others stay as they are.", bulkApply: "Apply entered levels", bulkInvalid: "Check the codes and levels. Duplicate codes are not allowed.", backup: "Download backup", restore: "Import backup", restoreInvalid: "Invalid Mod Tree v1 backup. Existing records were not changed.",
    source: "Formula source", method: "Score = log₁₀(Power) × [cost importance × log₁₀(MP/cost) + (1 − cost importance)]. A02, A03 and G22 follow the sheet's priority-unlock rule. This weighted heuristic is not a measured game efficiency.",
  },
};
